// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibhgydrxgclzykfhqved.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliaGd5ZHJ4Z2NsenlrZmhxdmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2ODM3ODMsImV4cCI6MjA1OTI1OTc4M30.C2e442tZ0G1pF48gmDx80AOeMZJV-L614AFYYkRM8A8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);